version: '3.7'

services:

  hivemq:
    container_name: hivemq
    image: hivemq/hivemq4:latest
    container_name: hivemq
    ports:
      - "1883:1883"   # Porta MQTT
      - "8080:8080"   # Console de administração (se disponível)
    secrets:
      - hivemq-user-secret
      - hivemq-password-secret
    volumes:
      - hivemq-data:/opt/hivemq/data
      - hivemq-config:/opt/hivemq/conf
    restart: unless-stopped
    networks:
      - iot-net

  influxdb:
    container_name: influxdb
    image: influxdb:2.7.5
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: iftm
      DOCKER_INFLUXDB_INIT_BUCKET: iotbiomedica
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - iot-net

  nodered:
    container_name: nodered
    build: .
    #image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nrdata:/data
    environment:
      - FLOWS=flows.json
    networks:
      - iot-net
    depends_on:
      - influxdb
      - hivemq


networks:
  iot-net:

secrets:
  influxdb2-admin-username:
    file: ~/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ~/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ~/.env.influxdb2-admin-token
  hivemq-user-secret:
    file: ~/.env.hivemq-user
  hivemq-password-secret:
    file: ~/.env.hivemq-password
volumes:
  influxdb2-data:
  influxdb2-config:
  grafana_data:
  node_red_data:
  hivemq-data:
  hivemq-config:
  
